name: Updating Production for IPPU

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Upload files to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "."
          target: "/var/www/ippu.org"

      - name: Run migrations, optimize, and restart Supervisor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/ippu.org
            php artisan migrate --force
            php artisan optimize:clear
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart all

      - name: Set proper permissions for storage and cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            sudo chgrp -R www-data /var/www/ippu.org/storage /var/www/ippu.org/bootstrap/cache
            sudo chmod -R ug+rwx /var/www/ippu.org/storage /var/www/ippu.org/bootstrap/cache
